GMM_Main/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Short_Code__c</fullName>
        <description>Created as part of new requirements from Khalid on 4/11/2016.</description>
        <label>Short Code</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GMM_Main/src/objects/Application3__c.object
<CustomObject>
    <description>SF-424</description>
    <fields>
        <fullName>Applicant_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicant/User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Applications1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application3__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Corporate_Program__c</fullName>
        <formula>NOFA_RFP__r.Corporate_Program__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Corporate Program</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Grantee_Status__c</fullName>
        <label>Application Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold Pending Resources</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Return for Re-work</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>NOFA_Fiscal_Yr__c</fullName>
        <formula>TEXT( NOFA_RFP__r.Fiscal_Yr__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>NOFO Fiscal Yr</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NOFA_RFP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NOFO/RFP ID</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR (3 AND (4 OR 5))</booleanFilter>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>State Commission Profile</value>
            </filterItems>
            <filterItems>
                <field>NOFA__c.Allow_Prime_Applicants_and_Sub_Applicant__c</field>
                <operation>equals</operation>
                <value>Yes</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>notEqual</operation>
                <value>State Commission Profile</value>
            </filterItems>
            <filterItems>
                <field>NOFA__c.Allow_Prime_Applicants_and_Sub_Applicant__c</field>
                <operation>equals</operation>
                <value>Yes, No</value>
            </filterItems>
            <filterItems>
                <field>NOFA__c.Allow_Prime_Applicants_and_Sub_Applicant__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>NOFA__c</referenceTo>
        <relationshipLabel>Application</relationshipLabel>
        <relationshipName>Application</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Prime_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prime Application</label>
        <referenceTo>Prime_Application__c</referenceTo>
        <relationshipLabel>Sub-Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Title__c</fullName>
        <label>Project Title</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Name</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Application</relationshipLabel>
        <relationshipName>Application</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type_of_Application__c</fullName>
        <description>Type of Application</description>
        <inlineHelpText>Please select Type of Application</inlineHelpText>
        <label>Type of Application</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Continuation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amendment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Application ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <recordTypes>
        <fullName>Application</fullName>
        <active>true</active>
        <label>Application</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GMM_Main/src/objects/NOFA__c.object
<CustomObject>
    <description>This is the first tab in the CNCS app</description>
    <fields>
        <fullName>Corporate_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Corporate Program Name</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>NOFAs_RFPs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fiscal_Yr__c</fullName>
        <label>NOFO Fiscal Year</label>
        <picklist>
            <picklistValues>
                <fullName>2002</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2003</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2004</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2005</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2006</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2007</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2008</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2009</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2010</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2011</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2012</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2013</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2014</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2015</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2016</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2017</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2018</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2019</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2020</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organization</label>
        <referenceTo>Organization__c</referenceTo>
        <relationshipName>NOFAs_RFPs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If your project is not found then add a new project under your Account.</inlineHelpText>
        <label>Project Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Project__c.Project__r.Status__c</field>
                <operation>notEqual</operation>
                <value>Closed</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>NOFOs/RFPs</relationshipLabel>
        <relationshipName>NOFAs_RFPs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>NOFO/RFP</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>NOFO/RFP ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NOFOs/RFPs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GMM_Main/src/objects/Organization__c.object
<CustomObject>
    <label>Organization</label>
    <nameField>
        <label>Organization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organization</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GMM_Main/src/objects/Prime_Application__c.object
<CustomObject>
    <fields>
        <fullName>Corporate_Program__c</fullName>
        <formula>NOFO_RFP__r.Corporate_Program__r.Name</formula>
        <label>Corporate Program</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prime_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prime Application</label>
        <referenceTo>Prime_Application__c</referenceTo>
        <relationshipLabel>Prime Applications</relationshipLabel>
        <relationshipName>Prime_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Name</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Prime Applications</relationshipLabel>
        <relationshipName>Prime_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Title__c</fullName>
        <description>Project_Name__r.Title__c</description>
        <formula>Project_Name__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Title</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type_of_Application__c</fullName>
        <label>Type of Application</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Continuation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amendment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Prime Application</label>
    <nameField>
        <label>Prime Application ID Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prime Applications</pluralLabel>
    <recordTypes>
        <fullName>Application</fullName>
        <active>true</active>
        <label>Application</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GMM_Main/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Short_Code__c</fullName>
        <label>Short Code</label>
        <length>4</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

GMM_Main/src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>CorporateProgram__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Corporate Program</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project_Director__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Director</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Organization__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Title__c</fullName>
        <label>Project Title</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Project Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GMM_Main/src/classes/ApplicationHelper.cls
public without sharing class ApplicationHelper {
    public static void checkApplicationforSameYr(list<Application3__c> newApps){
        
        system.debug('checkApplicationforSameYr');
        set<Id> projectIds = new set<Id>();
        list<Application3__c> appToUpdate = new list<Application3__c>();
        set<Id> nofaIds = new set<Id>();
        list<Project__c> projects = new list<Project__c>();              
        Id appRecordTypeId = Schema.SObjectType.Application3__c.getRecordTypeInfosByName().get('Application').getRecordTypeId();
        Id cpRecordTypeId = Schema.SObjectType.Application3__c.getRecordTypeInfosByName().get('Concept Paper').getRecordTypeId();
        map<Id,Project__c> pMap = new map<Id,Project__c>();
        system.debug('newApps= '+newApps);        
        for(Application3__c a: newApps){                
          if(a.Project__c != null && appRecordTypeId == a.RecordTypeId  && a.Type_of_Application__c == 'New'){
             projectIds.add(a.Project__c);
          }
          if(a.Project__c != null && cpRecordTypeId == a.RecordTypeId){
             projectIds.add(a.Project__c);
          }
        } 
        if(projectIds!=null && projectIds.size()>0){       
            projects = [Select p.Name, p.Id,p.Organization__c,Project_Title__c, (Select Id, Name,NOFA_RFP__c,Project_Title__c,NOFA_RFP__r.Fiscal_Yr__c,NOFA_Fiscal_Yr__c,Project__c,RecordTypeId From Application__r) From Project__c p where Id in : projectIds];        
            
            for(Project__c p: projects){ 
                pMap.put(p.Id,p);                                  
                if(p.Application__r!=null && p.Application__r.size()>0){
                    for(Application3__c a: p.Application__r){
                      if(a.RecordTypeId == appRecordTypeId || a.RecordTypeId == cpRecordTypeId) {
                        nofaIds.add(a.NOFA_RFP__c);
                      }  
                    }
                    
                }
            }
            
            for(Application3__c newApp: newApps){
                newApp.Project_Title__c = pMap.get(newApp.Project__c).Project_Title__c;
                if(newApp.NOFA_RFP__c!=null){
                 nofaIds.add(newApp.NOFA_RFP__c);
                }
            }
            system.debug('nofaIds = '+nofaIds);
            if(nofaIds!=null && nofaIds.size()>0){
                Map<Id,Nofa__c> nofaFiscalYrs = new Map<Id,Nofa__c>([Select Id,Fiscal_Yr__c,Corporate_Program__r.Short_Code__c from NOFA__c where Id in :nofaIds]);   
          
              
           
                for(Project__c p: projects){                
                    for(Application3__c newApp: newApps){                                     
                        if(p.Application__r!=null && p.Application__r.size()>0){                            
                            for(Application3__c a: p.Application__r){                                   
                                if(a.RecordTypeId == appRecordTypeId || a.RecordTypeId == cpRecordTypeId){                                  
                                  if(a.RecordTypeId == newApp.RecordTypeId){                                                                  
                                    if(a.Project__c == newApp.Project__c && newApp.NOFA_RFP__c!=null && a.NOFA_RFP__c == newApp.NOFA_RFP__c && (a.NOFA_Fiscal_Yr__c != '' && a.Nofa_Fiscal_yr__c != null) && a.NOFA_Fiscal_Yr__c == nofaFiscalYrs.get(newApp.NOFA_RFP__c).Fiscal_Yr__c){                            
                                        newApp.adderror('A project can only be attached to a single application/concept paper in a fiscal year');                           
                                    }
                                  }
                                }
                             } 
                        
                        }
                             
                    
                    }
                }
            }
        }
        
        
    
        
        
    } 
      
    
    
    /*public static boolean isDupeAppWithaDiffProject(Id orgId,Id nofaId,String yr){
        set<Id> projectIds = new set<Id>();
        list<Project__c> projects = new list<Project__c>();
        
        Account a = [Select a.Name, a.Id, (Select Name From Projects__r) From Account a where Id = :orgId];
        if(a!=null && a.Projects__r != null){
            for(Project__c p: a.Projects__r){
                projectIds.add(p.Id);
            }   
        }
        system.debug('project Ids = '+projectIds);
        projects = [Select p.Name, p.Id,p.Organization__c, (Select Id, Name,NOFA_RFP__c,NOFA_RFP__r.Fiscal_Yr__c,NOFA_Fiscal_Yr__c,Project__c From Application__r) From Project__c p where Id in : projectIds];        
        
        for(Project__c p: projects){
            if(p.Application__r!=null){
                for(Application3__c app: p.Application__r){                 
                    if(app.Nofa_RFP__c == nofaId && app.NOFA_Fiscal_Yr__c == yr){
                        return true;
                    }
                    
                }
            }
        }
        return false;
        
    }*/
    
    /*public static void populateOrg(list<Application3__c> newapps){
        set<Id> usrIds = new set<Id>();
        map<Id,Id> usrIdtoOrgId = new map<Id,Id>();
        for(Application3__c a: newapps){
            if(a.Applicant_User__c !=null){
                usrIds.add(a.Applicant_User__c);
            } 
        }
        system.debug('usrIds = '+usrIds);
        list<User> users = new list<User>([Select u.Name, u.Id, u.AccountId From User u where Id in :usrIds]);
        for(User u:users){
            if(u.AccountId!=null)
                usrIdtoOrgId.put(u.Id,u.AccountId);
        }
        system.debug('user map = '+usrIdtoOrgId);
        for(Application3__c a:newApps){
            if(usrIdtoOrgId.get(a.Applicant_User__c)!=null){
                a.Organization__c = usrIdtoOrgId.get(a.Applicant_User__c);
            }
        }
        
    }*/
    
    public static void shareApplicationsWithStateComission(list<Application3__c> newApps,map<Id,Application3__c> oldmap){
        Profile p = [Select Id,Name from Profile where Name = 'System Administrator'];
        if(userInfo.getProfileId()!=p.Id){
            set<Id> primeAppIds = new set<Id>();
            for(Application3__c a:newApps){
                
                if(a.Prime_Application__c!=null && oldmap != null && oldmap.get(a.Id).Grantee_Status__c == 'In Progress' && a.Grantee_Status__c != 'In Progress' ){
                    primeAppIds.add(a.Prime_Application__c);
                }
                if(a.Prime_Application__c!=null && oldmap == null && a.Grantee_Status__c != 'In Progress' ){
                    primeAppIds.add(a.Prime_Application__c);
                }
            
            }
            if(primeAppIds.size()>0){
                Map<Id,Prime_Application__c> primeApps = new Map<Id,Prime_Application__c>([Select Id,createdById,Project_Name__r.Organization__c from Prime_Application__c where id in :primeAppids]);
                list<Application3__Share> appShares = new list<Application3__Share>();
                list<AccountShare> accShares = new list<AccountShare>();
                if(primeApps.size()>0){
                    for(Application3__c a:newApps){
                        if(a.Prime_Application__c!=null){
                            Application3__Share aShare = new Application3__Share();
                            aShare.ParentId = a.Id;
                            aShare.userorgroupId = primeApps.get(a.Prime_Application__c).createdById;
                            aShare.AccessLevel = 'Edit';
                            appShares.add(aShare);
                            
                            AccountShare accShare = new AccountShare();
                            accShare.AccountId = a.Organization__c;
                            accShare.userorgroupId = primeApps.get(a.Prime_Application__c).createdById;
                            accShare.AccountAccessLevel = 'Read';
                            accShare.OpportunityAccessLevel = 'Read';
                            accShares.add(accShare);
                        }
                    }
                }
                if(appShares.size()>0){
                    insert appShares;
                }
                if(accShares.size()>0){
                    insert accShares;
                }
            }
        }
    }
    
    public static void shareApplications(list<Application3__c> newApps){
        Profile p = [Select Id,Name from Profile where Name = 'System Administrator'];
        if(userInfo.getProfileId()!=p.Id){
            set<Id> orgIds = new set<Id>();         
            set<Id> conIds = new set<Id>();
            map<Id,Application3__c> accIdtoAppId = new map<Id,Application3__c>();
            map<Id,Id> conNametoAccId = new map<Id,Id>();
            list<Application3__Share> appShares = new list<Application3__Share>();
            for(Application3__c a: newApps){
                if(a.Organization__c != null){
                    orgIds.add(a.Organization__c);
                    accIdtoAppId.put(a.Organization__c,a);
                }   
            }
            if(orgIds.size()>0){
                list<Account> accs = new list<Account>([Select (Select Id, LastName, FirstName, Name,AccountId From Contacts) From Account a where Id in :orgIds]);
                if(accs.size()>0){
                    for(Account a: accs){
                        if(a.Contacts.size()>0){
                            for(Contact c: a.Contacts){                              
                                conIds.add(c.id);                           
                                conNametoAccId.put(c.Id,c.AccountId);
                            }
                        }
                    }
                }
                if(conIds.size()>0){
                    set<Id> roleIds = new set<Id>();
                    list<User> users = new list<User>([Select Id,FirstName,LastName,Name,userRoleId,ContactId from User where ContactId in :conIds]);
                    if(users.size()>0){
                        for(User u: users){ 
                          if(u.Id!=userInfo.getUserId() && accIdtoAppId.get(conNametoAccId.get(u.ContactId))!= null && accIdtoAppId.get(conNametoAccId.get(u.ContactId)).OwnerId != u.Id){                               
                            Application3__Share aShare = new Application3__Share();
                            aShare.ParentId = accIdtoAppId.get(conNametoAccId.get(u.ContactId)).Id;
                            aShare.userorgroupId = u.Id;
                            aShare.AccessLevel = 'Edit';
                            appShares.add(aShare);
                          }                         
                        }
                    }                   
                }
                if(appshares.size()>0){
                    insert appshares;
                }
                
                
            }
        }
    }
}