GMM_Main/src/objects/Application3__c.object
<CustomObject>
    <description>SF-424</description>
    <fields>
        <fullName>Competitive_or_Formula__c</fullName>
        <description>This field is for Sub-Applications - Competitive or Formula.</description>
        <label>Competitive or Formula</label>
        <picklist>
            <picklistValues>
                <fullName>Competitive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Formula</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Grantee_Status__c</fullName>
        <label>Application Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold Pending Resources</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Return for Re-work</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Prime_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prime Application</label>
        <referenceTo>Prime_Application__c</referenceTo>
        <relationshipLabel>Sub-Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Application Status - CNCS Only</label>
        <picklist>
            <picklistValues>
                <fullName>Submitted to Prime</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recommended to CNCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected by Prime</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to CNCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted Late to CNCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waitlisted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returned for Rework</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected by CNCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Held for Formula</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awarded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold Pending Resources</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Prime Award Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Application ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <recordTypes>
        <fullName>Application</fullName>
        <active>true</active>
        <label>Application</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GMM_Main/src/objects/Prime_Application__c.object
<CustomObject>
    <fields>
        <fullName>CNCS_Status__c</fullName>
        <label>Application Status</label>
        <picklist>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recommended to CNCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to CNCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted Late to CNCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returned for Rework</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected by CNCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Held for Formula</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Awarded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepting Sub-Applications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed to Sub-Applicants</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Competitive_or_Formula__c</fullName>
        <label>Competitive or Formula</label>
        <picklist>
            <picklistValues>
                <fullName>Competitive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Formula</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Prime_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prime Application</label>
        <referenceTo>Prime_Application__c</referenceTo>
        <relationshipLabel>Prime Applications</relationshipLabel>
        <relationshipName>Prime_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Prime Application</label>
    <nameField>
        <label>Prime Application ID Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prime Applications</pluralLabel>
    <recordTypes>
        <fullName>Application</fullName>
        <active>true</active>
        <label>Application</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GMM_Main/src/classes/PrimeApplicationHelper.cls
public without sharing class PrimeApplicationHelper {

    public static void shareRecords(list<Prime_Application__c> primeApps){
        list<Profile> profiles = new list<Profile>([Select Id,Name from Profile where Name = 'System Administrator' or Name = 'Grantee Admin' or Name = 'Applicant']);
        map<String,Id> pMap = new map<String,Id>();
        for(Profile p: profiles){
            pMap.put(p.Name,p.Id);
        }
        if(userInfo.getProfileId()!=pMap.get('System Administrator')){
            //set<Id> roleIds = new set<Id>();
            list<User> users = new list<User>([Select Id,Name,userRoleId from User where isActive = true and (ProfileId = :pMap.get('Grantee Admin') or ProfileId = :pMap.get('Applicant'))]);
            
            if(users.size()>0){
                list<Prime_Application__Share> pshares = new list<Prime_Application__Share>();
                for(Prime_Application__c p: primeApps){
                    if(p.CNCS_Status__c == 'Accepting Sub-Applications'){
                        for(User u: users){
                            Prime_Application__Share pShare = new Prime_Application__Share();
                            pShare.ParentId = p.Id;
                            pShare.userorgroupId = u.Id;
                            pShare.AccessLevel = 'Read';
                            pShares.add(pShare);
                        }
                    }
                }
                if(pShares.size()>0){
                    insert pShares;
                }
            }
        }
    }
    
    public static void updateFormulaSubAppsToAwarded(map<Id,Prime_Application__c> oldRecs, map<Id,Prime_Application__c> newRecs){
        Id appRTId = Schema.SObjectType.Application3__c.getRecordTypeInfosByName().get('Application').getRecordTypeId();
        set<Id> primeAppIds = new set<Id>();        
        for(Id i: newRecs.keyset()){
            if(oldRecs.get(i).CNCS_Status__c!=newRecs.get(i).CNCS_Status__c && newRecs.get(i).CNCS_Status__c == 'Awarded' && newRecs.get(i).Competitive_or_Formula__c == 'Formula' ){
                primeAppIds.add(i);
            }
        }
        system.debug('primeAppIds = '+primeAppIds);
        if(primeAppIds.size()>0){
            list<Application3__c> formulasubApps = new list<Application3__c>([Select Id,Status__c, Grantee_Status__c from Application3__c where Prime_Application__c in :primeAppIds and RecordTypeId = :appRTId]);
            system.debug('formulaSubApps = '+FormulaSubApps);
            if(formulasubApps.size()>0){
                for(Application3__c a: formulasubApps){
                    //a.Grantee_Status__c = 'Awarded'
                    a.Status__c = 'Awarded';
                }
                update formulasubApps; 
            }       
        }
    }
    
    public static void updateSubAppsToAccepted(map<Id,Prime_Application__c> oldRecs, map<Id,Prime_Application__c> newRecs){
        Id appRTId = Schema.SObjectType.Application3__c.getRecordTypeInfosByName().get('Application').getRecordTypeId();
        set<Id> primeAppIds = new set<Id>();        
        for(Id i: newRecs.keyset()){
            if(oldRecs.get(i).CNCS_Status__c!=newRecs.get(i).CNCS_Status__c && newRecs.get(i).CNCS_Status__c == 'Accepted' ){
                primeAppIds.add(i);
            }
        }
        system.debug('primeAppIds = '+primeAppIds);
        if(primeAppIds.size()>0){
            list<Application3__c> subApps = new list<Application3__c>([Select Id,Status__c, Grantee_Status__c from Application3__c where Prime_Application__c in :primeAppIds and RecordTypeId = :appRTId and Status__c = 'Pending Prime Award Approval']);            
            if(subApps.size()>0){
                for(Application3__c a: subApps){
                    //a.Grantee_Status__c = 'Awarded'
                    a.Status__c = 'Accepted';
                }
                update subApps; 
            }       
        }
    }
}