GMM_Main/src/objects/Award__c.object
<CustomObject>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program_Name__c</referenceTo>
        <relationshipLabel>Award</relationshipLabel>
        <relationshipName>Award</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Award</label>
    <nameField>
        <label>Award ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Award</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GMM_Main/src/objects/Fund_Commitment__c.object
<CustomObject>
    <description>User Story 759 for Selecting the funding strip(Source) from the NOFO Object</description>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipLabel>Fund Commitment</relationshipLabel>
        <relationshipName>Fund_Commitment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Change__c</fullName>
        <label>Change</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Current_Amount__c</fullName>
        <label>Current Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Ending_FY__c</fullName>
        <label>Ending FY</label>
        <length>17</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fund__c</fullName>
        <description>Fund – Read only. [See Parse below]
o   Parse Fiscal Year Basis string into “Start FY” (numeric), “End FY” (numeric) and “Fund” (alpha-numeric).
o   Populate with “Fund” value</description>
        <label>Fund</label>
        <length>17</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Grant_Location__c</fullName>
        <label>Grant Location</label>
        <length>17</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Class__c</fullName>
        <label>Object Class</label>
        <length>17</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <length>17</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Purpose__c</fullName>
        <label>Purpose</label>
        <length>17</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_FY__c</fullName>
        <label>Start FY</label>
        <length>17</length>
        <type>Text</type>
    </fields>
    <label>Fund Commitment</label>
    <nameField>
        <label>Fund Commitment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fund Commitment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GMM_Main/src/classes/FundCommitmentsForAwardCntrl2.cls
public class FundCommitmentsForAwardCntrl2{

    public ApexPages.StandardController stdcontroller;
     public Award__c objAward{get;set;}
     public List<Fund_Commitment__c> lstFundCommitment{get;set;}
     public String strAwardId{get;set;}
    
     public ParseJSONUtil.CommitmentFundsForGrantIdJSON objDeserializedJson{get;set;}
     public List<ParseJSONUtil.CommitmentFundsForGrantIdData> lstCommitmentFundsForGrantIdData{get;set;}
    // public List<CommitmentFundsForGrantIdDataWrapper> lstCommitmentFundsForGrantIdDataWrapper{get;set;}
    public boolean opFlg{get;set;}
    public boolean ipFlg{get;set;}
    
    public boolean showPopup {get;set;}
    public Fund_Commitment__c objFormFundCommitment{get;set;}
    public String Start_FY{get;set;}
    
    
    
     
     public FundCommitmentsForAwardCntrl2(ApexPages.StandardController p_controller){
       this.stdcontroller= p_controller;
       
      // stdcontroller.addFields(new List<String>{'name'});
       
       this.objAward= (Award__c )stdController.getrecord();
       strAwardId=objAward.name;
       System.debug('***objAward***'+objAward);
      
      // lstCommitmentFundsForGrantIdDataWrapper=new List<CommitmentFundsForGrantIdDataWrapper>();
      opFlg=true;
      ipFlg=false;
      
      showPopup = false;
    }
    
    
    public PageReference openPopup()
    {   System.debug('****openPopup****');
        showPopup = true;
        objFormFundCommitment=new Fund_Commitment__c ();
        return null;
    }
    
    public PageReference Cancel()
    {
        System.debug('****Cancel****');
        showPopup = false;
        System.debug('***Start_FY***'+Start_FY);
        System.debug('***objFormFundCommitment***'+objFormFundCommitment);
        System.debug('***lstFundCommitment***'+lstFundCommitment);
        
        
        
        return null;
    }
    
    public string hidePopup(){
     //string MyString_From_Methode = 'Method called from js using Action function';
     System.debug('****ActionFunMethode****');
     showPopup = false;
     System.debug('***Start_FY***'+Start_FY);
     System.debug('***objFormFundCommitment***'+objFormFundCommitment);
     System.debug('***lstFundCommitment***'+lstFundCommitment);
     lstFundCommitment.add(objFormFundCommitment);
     System.debug('***lstFundCommitment***'+lstFundCommitment);
     
     return null;
    }
    
    
     public void invokeFcLines(){
        HttpResponse resp;
        String json;
        
            DemoHandShakingMuleSoft objDemo= new DemoHandShakingMuleSoft();
            try{
               resp= objDemo.makeACall(strAwardId);
               System.debug('***resp***'+resp);
               // the service is returning a line feed so parse it out
               json = resp.getBody().replace('\n', '');
               System.debug('***resp***'+resp );
               System.debug('***json***'+json );
              
               objDeserializedJson= new ParseJSONUtil.CommitmentFundsForGrantIdJSON();
                 
               ParseJSONUtil objParseJSONUtil= new ParseJSONUtil();
               objDeserializedJson=objParseJSONUtil.parseCommitmentFundsForGrantId(json);
               System.debug('***objDeserializedJson in invokeFcLines***'+objDeserializedJson);
               lstCommitmentFundsForGrantIdData = objDeserializedJson.lstData;
               System.debug('***lstCommitmentFundsForGrantIdData '+lstCommitmentFundsForGrantIdData );
               //copyData();
               copyJSONDataToFundCommitmentStruct();
                     
            }catch(System.CalloutException ce) {
                  System.debug('Callout error: '+ ce);
                  ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,ce.getMessage()));
                  //System.debug(resp.toString());
            }
            catch(Exception exc){
                System.debug('***exc***'+exc.getMessage());
            }
       
    }
    
   public void copyJSONDataToFundCommitmentStruct(){
           
            System.debug('***lstCommitmentFundsForGrantIdData '+lstCommitmentFundsForGrantIdData );
            lstFundCommitment =new List<Fund_Commitment__c>();
            Fund_Commitment__c objFundCommitment;
            for(ParseJSONUtil.CommitmentFundsForGrantIdData itrCommitmentFundsForGrantIdData   :lstCommitmentFundsForGrantIdData ){
                System.debug('***itrCommitmentFundsForGrantIdData***'+itrCommitmentFundsForGrantIdData  );  
                objFundCommitment=new Fund_Commitment__c();
                //objFundCommitment.Award__c=objAward.id;//itrCommitmentFundsForGrantIdData.DOC_NUM;
                objFundCommitment.Start_FY__c=itrCommitmentFundsForGrantIdData.FISCAL_YR_1_NBR;
                objFundCommitment.Ending_FY__c =itrCommitmentFundsForGrantIdData.FISCAL_YR_2_NBR;
                objFundCommitment.Fund__c=itrCommitmentFundsForGrantIdData.FUND_CD;
                objFundCommitment.Grant_Location__c=itrCommitmentFundsForGrantIdData.GRNT_LOCATION_NBR;
                objFundCommitment.Object_Class__c=itrCommitmentFundsForGrantIdData.OBJ_CLASS_CD;
                objFundCommitment.Program__c=itrCommitmentFundsForGrantIdData.PGM_MGR_CD;//PROG_ID;
                objFundCommitment.Purpose__c=itrCommitmentFundsForGrantIdData.PURPOSE_CD;
                objFundCommitment.Current_Amount__c=(itrCommitmentFundsForGrantIdData!=null && itrCommitmentFundsForGrantIdData.LINE_COMMITTED_AMT!=null)? Decimal.Valueof(itrCommitmentFundsForGrantIdData.LINE_COMMITTED_AMT):0;
                lstFundCommitment.add(objFundCommitment);
            }
             System.debug('***lstFundCommitment***'+lstFundCommitment);   
     
   }
   
   public void addNewRecord(){
       Fund_Commitment__c objFundCommitment=new Fund_Commitment__c();
       lstFundCommitment.add(objFundCommitment);
       ipFlg=true;
       System.debug('***lstFundCommitment***'+lstFundCommitment);
       System.debug('***ipFlg***'+ipFlg);
   
   }
   
   public void updateFundCommitment( ){
       String strBuildData='"buildData":"';
       boolean concatfromSecItr=false;
       integer line_num=1;
       if(lstFundCommitment!=null){
            System.debug('***lstFundCommitment.size()***'+lstFundCommitment.size());
       }
       for( Fund_Commitment__c itrObjFund_Commitment  :lstFundCommitment){
            
            Double chng=(itrObjFund_Commitment!=null && itrObjFund_Commitment.Change__c!=null)? Double.valueof(itrObjFund_Commitment.Change__c) : 0;
           // Decimal chng=(objCommitmentFundsForGrantIdData!=null && objCommitmentFundsForGrantIdData.Change!=null)? Decimal.valueof(objCommitmentFundsForGrantIdData.Change) : 0;
           /* if(itrObjFund_Commitment  !=null && itrObjFund_Commitment.Change__c!=null){
                chng= double.valueof(itrObjFund_Commitment.Change__c) ;
            }
            else{
               chng=0; 
            }*/
          
           Double total_amt=Double.valueof(itrObjFund_Commitment.Current_Amount__c)+chng;
           if (concatfromSecItr==true) {
                strBuildData+='~';
            }
            
            strBuildData+=line_num+'~';
            strBuildData+=total_amt+'~';
            strBuildData+='01'+'~';
            strBuildData+=itrObjFund_Commitment.Start_FY__c+'~';
            
            String tempFISCAL_YR_2_NBR='';
            tempFISCAL_YR_2_NBR=(itrObjFund_Commitment.Ending_FY__c!=null) ?(itrObjFund_Commitment.Ending_FY__c):tempFISCAL_YR_2_NBR;
            strBuildData+=tempFISCAL_YR_2_NBR+'~';
       
            strBuildData+=itrObjFund_Commitment.Fund__c+'~';
            ///strBuildData+=objCommitmentFundsForGrantIdData.PURPOSE_CD+'~';//-first char
            strBuildData+=(itrObjFund_Commitment.Purpose__c!=null )?(itrObjFund_Commitment.Purpose__c.SubString(0,1)):(itrObjFund_Commitment.Purpose__c);  ////-first char
            strBuildData+='~';
            
            strBuildData+=itrObjFund_Commitment.Purpose__c+'~';   
            strBuildData+=itrObjFund_Commitment.Grant_Location__c+'~';  
            strBuildData+=itrObjFund_Commitment.Object_Class__c+'~'; 
            
            strBuildData+=itrObjFund_Commitment.Program__c+'~';
            strBuildData+='~';
            
            strBuildData+='07/01/2014'+'~';
            strBuildData+='06/30/2015'+'~';
            
            strBuildData+='~~';
            concatfromSecItr=true;   
            line_num++;  
       }
       
        String strBody ='{ "grnt_id":"'+ strAwardId +'",';
        strBody +=strBuildData +'",';
        String strFormAction='"formAction":"AMEND",';
        strBody +=strFormAction;
        String strAmendJustificationTxt='"amendjustificationTxt": "Testing Mule Trasfer"'; 
        strBody +=strAmendJustificationTxt+'       }' ;
       
        System.debug('***strBody***'+strBody );
        invokeFundCommitment(strBody );

   }
   
   public void invokeFundCommitment(String strBody){
       HttpResponse resp;
       String json;
       // if(flagRecordsExists==false){
       DemoHandShakingMuleSoft objDemo= new DemoHandShakingMuleSoft();
       try{
               resp= objDemo.makeCallFundCommitmentSave(strAwardId,strBody);
               System.debug('***resp***'+resp);
               // the service is returning a line feed so parse it out
               json = resp.getBody().replace('\n', '');
               System.debug('***resp***'+resp );
               System.debug('***json***'+json );
               ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Info,json ));
        }catch(System.CalloutException ce) {
                  System.debug('Callout error: '+ ce);
                  ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,ce.getMessage()));
                  //System.debug(resp.toString());
        }
        catch(Exception exc){
                System.debug('***exc***'+exc.getMessage());
        }
   }
    
    


}