GMM_Main/src/objects/NOFA__c.object
<CustomObject>
    <description>This is the first tab in the CNCS app</description>
    <fields>
        <fullName>ConfiguredBudgetForms__c</fullName>
        <label>ConfiguredBudgetForms</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>NOFO/RFP</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>NOFO/RFP ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NOFOs/RFPs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GMM_Main/src/objects/Prime_Application__c.object
<CustomObject>
    <fields>
        <fullName>NOFO_RFP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NOFO/RFP</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR 3</booleanFilter>
            <filterItems>
                <field>NOFA__c.NOFA_Type__c</field>
                <operation>contains</operation>
                <value>Continuation, New &amp; Continuation</value>
            </filterItems>
            <filterItems>
                <field>$Source.CNCS_Corporate_Program__c</field>
                <operation>equals</operation>
                <valueField>NOFA__c.CNCS_Corporate_Program__c</valueField>
            </filterItems>
            <filterItems>
                <field>NOFA__c.NOFA_Type__c</field>
                <operation>equals</operation>
                <value>New, New &amp; Continuation</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>NOFA__c</referenceTo>
        <relationshipLabel>Prime Applications</relationshipLabel>
        <relationshipName>Prime_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Prime_Application_Configured_BudgetForms__c</fullName>
        <label>Prime Application Configured BudgetForms</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Prime_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prime Application</label>
        <referenceTo>Prime_Application__c</referenceTo>
        <relationshipLabel>Prime Applications</relationshipLabel>
        <relationshipName>Prime_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Prime Application</label>
    <nameField>
        <label>Prime Application ID Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prime Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GMM_Main/src/classes/CldBdgPrmAppMultiSelectCntrl.cls
public with sharing class CldBdgPrmAppMultiSelectCntrl{

    public ApexPages.StandardController stdcontroller;
    public SelectOption[] selectedBdgFrms { get; set; }
    public SelectOption[] allBdgFrms { get; set; }
    public String message { get; set; }
   
    public List<cb3__Budget_Settings__c> lstBudgetForm{get;set;}
      
    public Prime_Application__c prmApplication{get;set;}
    
    public Boolean showBdgFrm{get;set;} 
    
    public string selBudgetForm{get;set;}
    public NOFA__c nofa{get;set;}
    public String nofaId;
    
    public CldBdgPrmAppMultiSelectCntrl(){
      selectedBdgFrms = new List<SelectOption>();
    
    }
    
    public void readBudgetFormData(){
        selectedBdgFrms = new List<SelectOption>();
        lstBudgetForm= [SELECT id,name,cb3__Title__c FROM cb3__Budget_Settings__c ORDER BY cb3__Title__c];
         allBdgFrms= new List<SelectOption>();
        for (cb3__Budget_Settings__c objBudgetForm : lstBudgetForm) {
        if(objBudgetForm.cb3__Title__c!=null)
            allBdgFrms.add(new SelectOption(objBudgetForm.id ,objBudgetForm.cb3__Title__c));
        }
        
    }
    
     public CldBdgPrmAppMultiSelectCntrl(ApexPages.StandardController p_controller){
        selectedBdgFrms = new List<SelectOption>();
      this.stdcontroller= p_controller;
      this.prmApplication= (Prime_Application__c )stdController.getrecord();
      prmApplication=[select id,name,NOFO_RFP__c,Prime_Application_Configured_BudgetForms__c FROM Prime_Application__c where id= :prmApplication.id];
      if(prmApplication.NOFO_RFP__c!=null){
          nofaId=prmApplication.NOFO_RFP__c;
      //readBudgetFormData();
          retrieveSelectedBudgetFormData();
      }
    }
    
    public List<selectOption> getBudgetFormOptions(){
        List<SelectOption> budgetFormOptions = new List<SelectOption>(); 
        System.debug('***lstBudgetForm***'+lstBudgetForm);
        try{
            showBdgFrm=(lstBudgetForm==null) ? true:false;  
            if(lstBudgetForm!=null){
                for(cb3__Budget_Settings__c objBudgetForm : lstBudgetForm) {
                    if(objBudgetForm.cb3__Title__c!=null){
                        budgetFormOptions.add(new SelectOption(objBudgetForm.id ,objBudgetForm.cb3__Title__c ));                  
                    }
                }
           }
        }catch(Exception exc){  
                System.debug('error-getBudgetFormOptions'+ exc.getmessage()); 
       } 
        return budgetFormOptions;
    }
    
    public void retrieveSelectedBudgetFormData(){
    allBdgFrms= new List<SelectOption>();
      if(nofaId!=null && nofaId!=''){
          list<nofa__c> nofas =  new list<nofa__c>([select id,ConfiguredBudgetForms__c FROM NOFA__c WHERE id = :nofaId]);
          System.debug('***nofa***'+nofa);
          if(nofas!=null && nofas.size()>0){
              String strBdgFrmsid=nofas[0].ConfiguredBudgetForms__c ;
              List<String> lstBdgFrmIds=new List<String>();
              if(strBdgFrmsid!=null){
                  lstBdgFrmIds =strBdgFrmsid.split(',');
                   System.debug('***lstBdgFrmIds ***'+lstBdgFrmIds );
      
                  lstBudgetForm= [SELECT id,name,cb3__Title__c FROM cb3__Budget_Settings__c where id in :lstBdgFrmIds ORDER BY cb3__Title__c  ]; 
                   System.debug('***lstBudgetForm***'+lstBudgetForm);
                   for (cb3__Budget_Settings__c objBudgetForm : lstBudgetForm) {
                        if(objBudgetForm.cb3__Title__c!=null)
                            allBdgFrms.add(new SelectOption(objBudgetForm.id ,objBudgetForm.cb3__Title__c));
                        } 
                  }
          
          }
     }
        
    }
     public PageReference save() {
        message = 'Selected Budget Forms';
        String bdgFrmIds='';
        
        Boolean first = true;
        for ( SelectOption so : selectedBdgFrms ) {
            if (!first) {
                message += ', ';
                bdgFrmIds+=',';
            }
            message += so.getLabel() + ' (' + so.getValue() + ')';
            bdgFrmIds+=  so.getValue();
            first = false;
        }
        
  
        prmApplication.Prime_Application_Configured_BudgetForms__c =  bdgFrmIds;
        
        try{
            update prmApplication;
        }
        catch(Exception exc){
           System.debug('CldBdgPrmAppMultiSelectCntrl -Exception *** '+ exc);
        }
       
          //List<Database.SaveResult> resultList  = Database.update(listToUpsert, false);
          return null;       
    }
    
    
    
    




}